name: Orchestrator
run-name: ${{ format('Orchestrator ({0} {1} {2})', github.event_name, inputs.run_light, inputs.run_heavy)  }}
      
on:
  workflow_call:
    inputs:
      provision_mode:
        description: 'Provision mode (if set to initial it will use ubuntu-latest image)'
        type: string
        default: 'regular'
      loop:
        description: 'Loop the action'
        type: string
        default: "no"
      run_light:
        description: 'Run light VMs'
        type: string
        default: "no"
      run_heavy:
        description: 'Run heavy VMs'
        type: string
        default: "no"
      workflow_name:
        description: 'Name of the workflow to run'
        type: string
        default: 'orchestrator.yaml'
  workflow_dispatch:
    inputs:
      provision_mode:
        description: 'Provision mode (if set to initial it will use ubuntu-latest image)'
        type: choice
        options:
          - initial
          - regular
        required: true
        default: 'regular'
      loop:
        description: 'Loop the action'
        type: choice
        options:
          - "yes"
          - "no"
        required: false
        default: "no"
      run_light:
        description: 'Run light VMs'
        type: choice
        options:
          - "yes"
          - "no"
        required: false
        default: "yes"
      run_heavy:
        description: 'Run heavy VMs'
        type: choice
        options:
          - "yes"
          - "no"
        required: false
        default: "yes"
      workflow_name:
        description: 'Name of the workflow to run'
        type: choice
        options:
          - orchestrator-light.yaml
          - orchestrator-heavy.yaml
        required: true
        default: 'orchestrator-light.yaml'

jobs:
  light:
    name: Populate light VMs
    if: ${{ inputs.run_light == 'yes' }}
    uses: ./.github/workflows/scheduler.yaml
    secrets: inherit
    with:
      max_vms_to_create: 5
      vms_ttl: "86400"
      flavor: light
      provision_mode: ${{ inputs.provision_mode || 'regular' }}
      loop: ${{ inputs.provision_mode == 'initial' && 'no' || (inputs.loop || 'no') }}

  heavy:
    name: Populate heavy VMs
    if: ${{ inputs.run_heavy == 'yes' }}
    uses: ./.github/workflows/scheduler.yaml
    secrets: inherit
    with:
      max_vms_to_create: 1
      vms_ttl: "86400"
      flavor: heavy
      provision_mode: ${{ inputs.provision_mode || 'regular' }}
      loop: ${{ inputs.provision_mode == 'initial' && 'no' || (inputs.loop == 'yes' && 'yes' || 'no') }}
  
  # restart:
  #   name: Run gh cli to run orchestrator-proxy with the same arguments, which will start orchestrator.yaml if not cancelled and looped
  #   if: ${{ !cancelled() }}
  #   runs-on: ${{ inputs.provision_mode == 'initial' && fromJson('["ubuntu-latest"]') || fromJson('["self-hosted", "runner_light"]') }}
  #   needs: 
  #     - light
  #     - heavy
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         sparse-checkout: '.github'
  #     - name: Set up gh cli
  #       uses: ./.github/actions/gh_cli
  #     - name: Run gh cli to start this workflow with the same arguments
  #       if: ${{ always() }}
  #       shell: bash --noprofile --norc -eo pipefail -x {0} 
  #       run: |
  #         gh workflow run orchestrator-proxy.yaml -R "${GITHUB_REPO}" \
  #           --field provision_mode="${PROVISION_MODE}" \
  #           --field loop="${LOOP}" \
  #           --field run_light="${RUN_LIGHT}" \
  #           --field run_heavy="${RUN_HEAVY}" \  
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  #         GITHUB_REPO: ${{ github.repository }}
  #         PROVISION_MODE: 'regular'
  #         LOOP: ${{ inputs.provision_mode == 'initial' && 'no' || 'yes' }}
  #         RUN_LIGHT: ${{ inputs.run_light }}
  #         RUN_HEAVY: ${{ inputs.run_heavy }}
  #         WORKFLOW_NAME: ${}
