name: Scheduled maintaning of VMs count
run-name: ${{ format('Scheduled maintaning of VMs count ({0})', github.event_name) }}
      
on:
  schedule:
    - cron: "5,20,35,50 * * * *"
  workflow_dispatch:
    inputs:
      provision_mode:
        description: 'Provision mode (if set to initial it will use ubuntu-latest image)'
        type: choice
        options:
          - initial
          - regular
        required: true
        default: 'regular'

jobs:
  light:
    name: Populate light VMs
    uses: ./.github/workflows/populate.yaml
    secrets: inherit
    with:
      max_vms_to_create: 5
      vms_ttl: "86400"
      flavor: light
      provision_mode: ${{ inputs.provision_mode || 'regular' }}
  heavy:
    name: Populate heavy VMs
    uses: ./.github/workflows/populate.yaml
    secrets: inherit
    with:
      max_vms_to_create: 1
      vms_ttl: "86400"
      flavor: heavy
      provision_mode: ${{ inputs.provision_mode || 'regular' }}
